require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.0.0
  TargetRailsVersion: 7.0.4
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/bundle/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 23

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false
